import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import ThemeSwitcher from "@/components/darkmode/ThemeSwitcher";
import ReactQueryProvider from "./ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bgColor`}>
        <ReactQueryProvider>
          <Provider>{children}</Provider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
